timer:
  reminder: "30s"
  phases:
    sleeping: "5m"
    purchasing: "5m"
    winning: "10s"

winner:
  title:
    enabled: true
    title: "&6&lJACKPOT"
    subtitle: "+{money}$"
    steps: 500
    interval: 1
    fade-in: 20
    fade-out: 20

ticket-cost: 1000.0
min-players: 5

tax:
  enabled: true
  percentage: 10.0
  permission: "arcanejackpot.vip"

eco-format:
  enabled: true
  decimals: 1
  values:
    k: "K"
    m: "M"
    b: "B"